### ISSUE TITLE
Clarify what "outdated" means

### ISSUE THREAD

**Issue by juliangilbey** [kpcyrd/cargo-debstatus#5]
Hi!  I'm new to rust, but having looked through the source code, I can't fathom how deb.outdated could ever be set to true.  Nevertheless, it does seem to be sometimes, for example, keyring 0.8.0 reports:
`secret-service v1.0.0 (outdated)`.

Now it is not clear to me what this means: does it mean that there is a Debian package, but for an older version of this crate, or does it mean that there is a Debian package for a newer version of this crate, or perhaps that there is no Debian package, but this is also an out-of-date crate?

So it strikes me that there are actually two separate things that would be worth reporting on:

(1) Is this crate version up-to-date with the latest crate available on crate.io?

(2) Is this crate version up-to-date with the latest package available in Debian sid?

At the very least, clarifying what "outdated" means would be really helpful.

Thanks!

**Comment by kpcyrd** [comment]
hmm, let me reply in two steps: For your specific case `keyring 0.8.0` is compatible with the latest `secret-service` release (1.1.0), but `Cargo.lock` wants an older one. Running `cargo update` fixes the `(outdated)` indicator.

In another, more complicated example, consider:

- you have `foo 0.1.0` in your dependency tree
- `foo 0.2.0` is the latest version on crates.io
- debian either doesn't have a package for foo, or the package contains 0.2.0

In that case `cargo-debstatus` would indicate your `foo 0.1.0` dependency as `(outdated)` because we would explicitly need to package an old version of the crate and create a `rust-foo-0.1` package. We can, if we really need to, but we would rather try to get the packages to update their dependency or apply a patch downstream to update the dependency.

**Comment by juliangilbey** [comment]
Thanks - that's really informative!  So can I check I've understood correctly?  An '(outdated)' flag *always* means that two things are true: the package is behind the crates.io version *and* the specified version does not exist in the Debian archive.  Then there are two possible solutions: update the dependency (using, eg, `cargo update`), or package the outdated dependency (if updating it is not a possibility).

Best wishes,

Julian

**Comment by kpcyrd** [comment]
Yes, that's correct!

To be more precise, there are 3 possible solutions:
- update the dependency in the rust project
- update the dependency in debian by writing a patch
- package the outdated dependency (this requires manual approval by the ftp-masters and is more a last resort option)
